clear;
clc;
syms u0old v0old w0old T0old Sn0old Sb0old Phi0old Theta0old O2mega0old O3mega0old real;
syms u0new v0new w0new T0new Sn0new Sb0new Phi0new Theta0new O2mega0new O3mega0new real;
syms u1old v1old w1old T1old Sn1old Sb1old Phi1old Theta1old O2mega1old O3mega1old real;
syms u1new v1new w1new T1new Sn1new Sb1new Phi1new Theta1new O2mega1new O3mega1new real;
syms M ma E A I pi rho d0 Cdt Cdn Cdb real;
syms deltaT deltaS real;
syms Vx Vy Vz real;
syms Gx Gy Gz real;

%uu0 = u0old - Vx*cos(Phi0old)*cos(Theta0old) - Vy*cos(Theta0old)*sin(Phi0old) + Vz* sin(Theta0old)
%vv0 = v0old - Vy*cos(Phi0old) + Vx*sin(Phi0old)
%ww0 = w0old - Vx*cos(Phi0old)*sin(Theta0old) -Vy*sin(Phi0old)*sin(Theta0old) - Vz*cos(Theta0old)

%QG1 = -Gx*cos(Phi0old)*cos(Theta0old) - Gy*cos(Theta0old)*sin(Phi0old) + Gz*sin(Theta0old)
%QG2 = -Gy*cos(Phi0old) + Gx*sin(Phi0old)
%QG3 = -Gx*cos(Phi0old)*sin(Theta0old) - Gy*sin(Phi0old)*sin(Theta0old) - Gz*cos(Theta0old)


%Q0old = str2sym('[-O2mega0old*Sb0old+O3mega0old*Sn0old+(QG1)+0.5*pi*rho*d0*Cdt*(uu0)*abs(uu0)*sqrt(1+(T0old/(E*A)));-O3mega0old*T0old-tan(Theta0old)*O3mega0old*Sb0old+(QG2)+0.5*rho*d0*Cdn*(vv0)*sqrt((vv0)^2+(ww0)^2)*sqrt(1+(T0old/(E*A)));O3mega0old*tan(Theta0old)*Sn0old+O2mega0old*T0old+(QG3)+0.5*rho*d0*Cdb*(ww0)*sqrt((vv0)^2+(ww0)^2)*sqrt(1+(T0old/(E*A)));-O2mega0old*w0old+O3mega0old*v0old;-O3mega0old*u0old-tan(Theta0old)*O3mega0old*w0old;-tan(Theta0old)*O3mega0old*v0old-O2mega0old*u0old;E*I*O3mega0old*O3mega0old*tan(Theta0old)-Sb0old*(1+(T0old/(E*A)))^3;-E*I*O2mega0old*O3mega0old*tan(Theta0old)+Sn0old*(1+(T0old/(E*A)))^3;-O2mega0old;-O3mega0old]');

Q0old = str2sym('[-O2mega0old*Sb0old+O3mega0old*Sn0old+(-Gx*cos(Phi0old)*cos(Theta0old) - Gy*cos(Theta0old)*sin(Phi0old) + Gz*sin(Theta0old))+0.5*pi*rho*d0*Cdt*(u0old - Vx*cos(Phi0old)*cos(Theta0old) - Vy*cos(Theta0old)*sin(Phi0old) + Vz* sin(Theta0old))*abs(u0old - Vx*cos(Phi0old)*cos(Theta0old) - Vy*cos(Theta0old)*sin(Phi0old) + Vz* sin(Theta0old))*sqrt(1+(T0old/(E*A)));-O3mega0old*T0old-tan(Theta0old)*O3mega0old*Sb0old+(-Gy*cos(Phi0old) + Gx*sin(Phi0old))+0.5*rho*d0*Cdn*(v0old - Vy*cos(Phi0old) + Vx*sin(Phi0old))*sqrt((v0old - Vy*cos(Phi0old) + Vx*sin(Phi0old))^2+(w0old - Vx*cos(Phi0old)*sin(Theta0old) -Vy*sin(Phi0old)*sin(Theta0old) - Vz*cos(Theta0old))^2)*sqrt(1+(T0old/(E*A)));O3mega0old*tan(Theta0old)*Sn0old+O2mega0old*T0old+(-Gx*cos(Phi0old)*sin(Theta0old) - Gy*sin(Phi0old)*sin(Theta0old) - Gz*cos(Theta0old))+0.5*rho*d0*Cdb*(w0old - Vx*cos(Phi0old)*sin(Theta0old) -Vy*sin(Phi0old)*sin(Theta0old) - Vz*cos(Theta0old))*sqrt((v0old - Vy*cos(Phi0old) + Vx*sin(Phi0old))^2+(w0old - Vx*cos(Phi0old)*sin(Theta0old) -Vy*sin(Phi0old)*sin(Theta0old) - Vz*cos(Theta0old))^2)*sqrt(1+(T0old/(E*A)));-O2mega0old*w0old+O3mega0old*v0old;-O3mega0old*u0old-tan(Theta0old)*O3mega0old*w0old;-tan(Theta0old)*O3mega0old*v0old-O2mega0old*u0old;E*I*O3mega0old*O3mega0old*tan(Theta0old)-Sb0old*(1+(T0old/(E*A)))^3;-E*I*O2mega0old*O3mega0old*tan(Theta0old)+Sn0old*(1+(T0old/(E*A)))^3;-O2mega0old;-O3mega0old]');
Q0new = str2sym('[-O2mega0new*Sb0new+O3mega0new*Sn0new+(-Gx*cos(Phi0new)*cos(Theta0new) - Gy*cos(Theta0new)*sin(Phi0new) + Gz*sin(Theta0new))+0.5*pi*rho*d0*Cdt*(u0new - Vx*cos(Phi0new)*cos(Theta0new) - Vy*cos(Theta0new)*sin(Phi0new) + Vz* sin(Theta0new))*abs(u0new - Vx*cos(Phi0new)*cos(Theta0new) - Vy*cos(Theta0new)*sin(Phi0new) + Vz* sin(Theta0new))*sqrt(1+(T0new/(E*A)));-O3mega0new*T0new-tan(Theta0new)*O3mega0new*Sb0new+(-Gy*cos(Phi0new) + Gx*sin(Phi0new))+0.5*rho*d0*Cdn*(v0new - Vy*cos(Phi0new) + Vx*sin(Phi0new))*sqrt((v0new - Vy*cos(Phi0new) + Vx*sin(Phi0new))^2+(w0new - Vx*cos(Phi0new)*sin(Theta0new) -Vy*sin(Phi0new)*sin(Theta0new) - Vz*cos(Theta0new))^2)*sqrt(1+(T0new/(E*A)));O3mega0new*tan(Theta0new)*Sn0new+O2mega0new*T0new+(-Gx*cos(Phi0new)*sin(Theta0new) - Gy*sin(Phi0new)*sin(Theta0new) - Gz*cos(Theta0new))+0.5*rho*d0*Cdb*(w0new - Vx*cos(Phi0new)*sin(Theta0new) -Vy*sin(Phi0new)*sin(Theta0new) - Vz*cos(Theta0new))*sqrt((v0new - Vy*cos(Phi0new) + Vx*sin(Phi0new))^2+(w0new - Vx*cos(Phi0new)*sin(Theta0new) -Vy*sin(Phi0new)*sin(Theta0new) - Vz*cos(Theta0new))^2)*sqrt(1+(T0new/(E*A)));-O2mega0new*w0new+O3mega0new*v0new;-O3mega0new*u0new-tan(Theta0new)*O3mega0new*w0new;-tan(Theta0new)*O3mega0new*v0new-O2mega0new*u0new;E*I*O3mega0new*O3mega0new*tan(Theta0new)-Sb0new*(1+(T0new/(E*A)))^3;-E*I*O2mega0new*O3mega0new*tan(Theta0new)+Sn0new*(1+(T0new/(E*A)))^3;-O2mega0new;-O3mega0new]');
Q1old = str2sym('[-O2mega1old*Sb1old+O3mega1old*Sn1old+(-Gx*cos(Phi1old)*cos(Theta1old) - Gy*cos(Theta1old)*sin(Phi1old) + Gz*sin(Theta1old))+0.5*pi*rho*d0*Cdt*(u1old - Vx*cos(Phi1old)*cos(Theta1old) - Vy*cos(Theta1old)*sin(Phi1old) + Vz* sin(Theta1old))*abs(u1old - Vx*cos(Phi1old)*cos(Theta1old) - Vy*cos(Theta1old)*sin(Phi1old) + Vz* sin(Theta1old))*sqrt(1+(T1old/(E*A)));-O3mega1old*T1old-tan(Theta1old)*O3mega1old*Sb1old+(-Gy*cos(Phi1old) + Gx*sin(Phi1old))+0.5*rho*d0*Cdn*(v1old - Vy*cos(Phi1old) + Vx*sin(Phi1old))*sqrt((v1old - Vy*cos(Phi1old) + Vx*sin(Phi1old))^2+(w1old - Vx*cos(Phi1old)*sin(Theta1old) -Vy*sin(Phi1old)*sin(Theta1old) - Vz*cos(Theta1old))^2)*sqrt(1+(T1old/(E*A)));O3mega1old*tan(Theta1old)*Sn1old+O2mega1old*T1old+(-Gx*cos(Phi1old)*sin(Theta1old) - Gy*sin(Phi1old)*sin(Theta1old) - Gz*cos(Theta1old))+0.5*rho*d0*Cdb*(w1old - Vx*cos(Phi1old)*sin(Theta1old) -Vy*sin(Phi1old)*sin(Theta1old) - Vz*cos(Theta1old))*sqrt((v1old - Vy*cos(Phi1old) + Vx*sin(Phi1old))^2+(w1old - Vx*cos(Phi1old)*sin(Theta1old) -Vy*sin(Phi1old)*sin(Theta1old) - Vz*cos(Theta1old))^2)*sqrt(1+(T1old/(E*A)));-O2mega1old*w1old+O3mega1old*v1old;-O3mega1old*u1old-tan(Theta1old)*O3mega1old*w1old;-tan(Theta1old)*O3mega1old*v1old-O2mega1old*u1old;E*I*O3mega1old*O3mega1old*tan(Theta1old)-Sb1old*(1+(T1old/(E*A)))^3;-E*I*O2mega1old*O3mega1old*tan(Theta1old)+Sn1old*(1+(T1old/(E*A)))^3;-O2mega1old;-O3mega1old]');
Q1new = str2sym('[-O2mega1new*Sb1new+O3mega1new*Sn1new+(-Gx*cos(Phi1new)*cos(Theta1new) - Gy*cos(Theta1new)*sin(Phi1new) + Gz*sin(Theta1new))+0.5*pi*rho*d0*Cdt*(u1new - Vx*cos(Phi1new)*cos(Theta1new) - Vy*cos(Theta1new)*sin(Phi1new) + Vz* sin(Theta1new))*abs(u1new - Vx*cos(Phi1new)*cos(Theta1new) - Vy*cos(Theta1new)*sin(Phi1new) + Vz* sin(Theta1new))*sqrt(1+(T1new/(E*A)));-O3mega1new*T1new-tan(Theta1new)*O3mega1new*Sb1new+(-Gy*cos(Phi1new) + Gx*sin(Phi1new))+0.5*rho*d0*Cdn*(v1new - Vy*cos(Phi1new) + Vx*sin(Phi1new))*sqrt((v1new - Vy*cos(Phi1new) + Vx*sin(Phi1new))^2+(w1new - Vx*cos(Phi1new)*sin(Theta1new) -Vy*sin(Phi1new)*sin(Theta1new) - Vz*cos(Theta1new))^2)*sqrt(1+(T1new/(E*A)));O3mega1new*tan(Theta1new)*Sn1new+O2mega1new*T1new+(-Gx*cos(Phi1new)*sin(Theta1new) - Gy*sin(Phi1new)*sin(Theta1new) - Gz*cos(Theta1new))+0.5*rho*d0*Cdb*(w1new - Vx*cos(Phi1new)*sin(Theta1new) -Vy*sin(Phi1new)*sin(Theta1new) - Vz*cos(Theta1new))*sqrt((v1new - Vy*cos(Phi1new) + Vx*sin(Phi1new))^2+(w1new - Vx*cos(Phi1new)*sin(Theta1new) -Vy*sin(Phi1new)*sin(Theta1new) - Vz*cos(Theta1new))^2)*sqrt(1+(T1new/(E*A)));-O2mega1new*w1new+O3mega1new*v1new;-O3mega1new*u1new-tan(Theta1new)*O3mega1new*w1new;-tan(Theta1new)*O3mega1new*v1new-O2mega1new*u1new;E*I*O3mega1new*O3mega1new*tan(Theta1new)-Sb1new*(1+(T1new/(E*A)))^3;-E*I*O2mega1new*O3mega1new*tan(Theta1new)+Sn1new*(1+(T1new/(E*A)))^3;-O2mega1new;-O3mega1new]');